#!/bin/bash

# Icon Generation Helper Script for SkillSwap PWA
# This script helps you know what icons are needed and where to put them

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       SkillSwap PWA - Icon Generation Helper                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 Icon files needed in: ./public/icons/"
echo ""
echo "Required Icon Sizes:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  icon-192x192.png"
echo "    Size: 192 × 192 pixels"
echo "    Purpose: Regular icon for home screen"
echo ""
echo "2️⃣  icon-512x512.png"
echo "    Size: 512 × 512 pixels"
echo "    Purpose: Large icon for splash screens"
echo ""
echo "3️⃣  icon-maskable-192x192.png"
echo "    Size: 192 × 192 pixels"
echo "    Purpose: Adaptive icon (20% padding from edges)"
echo ""
echo "4️⃣  icon-maskable-512x512.png"
echo "    Size: 512 × 512 pixels"
echo "    Purpose: Adaptive icon large version"
echo ""
echo "5️⃣  screenshot-1.png"
echo "    Size: 540 × 720 pixels"
echo "    Purpose: Mobile/narrow display screenshot"
echo ""
echo "6️⃣  screenshot-2.png"
echo "    Size: 1280 × 720 pixels"
echo "    Purpose: Desktop/wide display screenshot"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 How to Generate Icons:"
echo ""
echo "Option 1: PWABuilder (Recommended) 🏆"
echo "  1. Visit: https://www.pwabuilder.com/"
echo "  2. Upload your logo/design"
echo "  3. Select all sizes"
echo "  4. Download ZIP"
echo "  5. Extract icons to ./public/icons/"
echo ""
echo "Option 2: Real Favicon Generator"
echo "  1. Visit: https://realfavicongenerator.net/"
echo "  2. Upload image"
echo "  3. Customize for each platform"
echo "  4. Download and place in ./public/icons/"
echo ""
echo "Option 3: Online Icon Generator"
echo "  1. Visit: https://favicon-generator.org/"
echo "  2. Upload or design icon"
echo "  3. Generate sizes"
echo "  4. Download to ./public/icons/"
echo ""
echo "Option 4: Use Design Tool (Figma, Adobe XD)"
echo "  1. Design 512×512 logo"
echo "  2. Export as PNG"
echo "  3. Scale to other sizes"
echo "  4. Save to ./public/icons/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Maskable Icon Tips:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Keep main content in center 60% of icon"
echo "  • Leave 20% padding on all edges"
echo "  • Test at: https://maskable.app/"
echo "  • Should look good on any background color"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🛠️  Once you have icons:"
echo ""
echo "  1. Copy all PNG files to: ./public/icons/"
echo "  2. Run build: npm run build"
echo "  3. Test locally: npm run preview"
echo "  4. Open DevTools (F12) → Application tab"
echo "  5. Check manifest.json loads correctly"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Checklist:"
echo "  [ ] Icon files created"
echo "  [ ] Files copied to ./public/icons/"
echo "  [ ] npm run build executed"
echo "  [ ] npm run preview working"
echo "  [ ] Manifest loads in DevTools"
echo "  [ ] Service Worker registered"
echo "  [ ] Install banner appears"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
